name: confparser

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python 3.8.2
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2

    - name: Install PyYAML
      run: pip3 install PyYAML
    - name: Install pytest
      run: pip3 install pytest
    - name: Testing
      run: pytest